files:
  - source: /src/MCM.Publish/_Module/ModuleData/Languages/EN/*.xml
    ignore:
      - /src/MCM.Publish/_Module/ModuleData/Languages/EN/language_data.xml
    translation: /src/MCM.Publish/_Module/ModuleData/Languages/%two_letters_code%/%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - '/LanguageData[@id],/LanguageData[@name],/LanguageData[@subtitle_extension],/LanguageData[@supported_iso],/LanguageData/strings/string[@text]'
