apiRules:
- exclude:
    uidRegex: ^HarmonyLib\.BUTR\.Extensions$
    type: Namespace
- exclude:
    uidRegex: ^Bannerlord\.BUTR\.Shared$
    type: Namespace
- exclude:
    uidRegex: ^Bannerlord\.DependencyInjection$
    type: Namespace
