name: Daily Code Format Check

on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
  workflow_dispatch:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Code Formatting
        uses: butr/actions-code-format-setup@v1
        with:
          workspace: "src/Mod Configuration Menu.sln"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: aragas
          reviewers: aragas
