name: Nexusmods Deployment

on:
  push:
    branches:
      - master
      - v3_nexusmods

jobs:

  artifact:
    name: Publish to GitHub Actions as Artifact
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/Bannerlord-Unofficial-Tools-Resources/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build MCM.Standalone (Release)
      run: dotnet build MCM.Standalone/MCM.Standalone.csproj --configuration Release -p:GameFolder="$pwd/bannerlord" -p:GITHUB_ACTIONS="false"
      shell: pwsh
    
    - name: Build MCM.Implementation.MBO (Release)
      run: dotnet build MCM.Implementation.MBO/MCM.Implementation.MBO.csproj --configuration Release -p:GameFolder="$pwd/bannerlord" -p:GITHUB_ACTIONS="false"
      shell: pwsh
    
    - name: Build MCM.Implementation.ModLib (Release)
      run: dotnet build MCM.Implementation.ModLib/MCM.Implementation.ModLib.csproj --configuration Release -p:GameFolder="$pwd/bannerlord" -p:GITHUB_ACTIONS="false"
      shell: pwsh

    - name: Zip MCM.Standalone
      uses: DuckSoft/create-7z-action@v1.0
      with:
        pathSource: bannerlord
        pathTarget: MCM.Standalone.zip

    - name: Upload MCM.Standalone.zip as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MCM.Standalone.zip
        path: MCM.Standalone.zip

  nexusmods:
    name: Publish to nexusmods
    runs-on: ubuntu-latest
    needs: artifact
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: MCM.Standalone.zip
    
    - name: Display structure of downloaded files
      run: ls -R
